[phases.setup]
nixPkgs = ["python310", "nodejs-18_x"]

[phases.build]
cmds = [
    "cd frontend && npm install && npm run build",
    "cd backend && pip install -r requirements.txt"
]

[start]
cmd = "gunicorn --directory backend app:app"